/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7azCamZ4Vl2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"

export function check() {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Choose your product</CardTitle>
        <CardDescription>Select the product or service youre interested in.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select a product" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Product 1</SelectItem>
                <SelectItem value="product2">Product 2</SelectItem>
                <SelectItem value="service1">Service 1</SelectItem>
                <SelectItem value="service2">Service 2</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
          <div className="flex items-center space-x-2">
            <Checkbox id="terms" />
            <Label htmlFor="terms">I accept the terms and conditions</Label>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
