/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9jNqnzmOptK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Taviraj } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function CreditoDirecto21() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-4 lg:py-12 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">Líneas de Crédito Directo</h1>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Crédito sin intermediarios financieros con y sin tasa compensada, dirigido a Entidades Territoriales
                    como Gobernaciones, Alcaldías y Entidades Públicas para proyectos en los 12 sectores estratégicos.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 py-12 lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/compromiso-reactivacion-colombia-2.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Reactivación Colombia Tramo 2</h3>
                <p className="text-muted-foreground text-center">
                  Tasa Compensada.  Financiación de Proyectos y/o Gastos de Inversión.  <br/>Adicionamos $800.000 millones.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Solicitar Crédito
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50  text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/catastro-multiproposito.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Catastro Multipropósito.</h3>
                <p className="text-muted-foreground text-center">
                  Tasa Compensada. Apoyamos la actualización del Catastro Multipropósito para lograr metas y objetivos de los planes de desarrollo territorial. <br/>$87.415 millones.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Solicitar Crédito
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50  text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                </div>
              </div><div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/inversion-rural.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Inversión Rural.</h3>
                <p className="text-muted-foreground text-center">
                  Inversiones estratégicas en electrificación, equipos y maquinaria, transporte especializado, infraestructura de transformación y desarrollo de vías terciarias.<br/>$100.000 millones.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Solicitar Crédito
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50  text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/eficiencia-energetica.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Eficiencia Energética</h3>
                <p className="text-muted-foreground text-center">
                  Financiación de proyectos del sector energético.  Generación, comercialización, distribución, transmisión, alamcenamiento y capital de trabajo para reducir gases de efecto invernadero.<br/>$1.3 Billones.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Solicitar Crédito
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50  text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/compromiso-valle-del-cauca.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Valle Del Cauca</h3>
                <p className="text-muted-foreground text-center">
                  Apoyamos a los distritos y municipios para que financien proyectos de inversión que permitan dinamizar sus economías, reactivar  la inversión publica y generar empleo. <br/> $50 mil millones.
                </p>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Solicitar Crédito
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50  text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                </div>
              </div>            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                ¿Como funciona el Crédito Directo?
              </h2>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              El Credito Directo significa que no tiene intermediario financiero, por lo cual permite obtener mejores tasas de interes.   Puede ser con tasa compensada o sin tasa compensada.  También Otorgamos junto a entidades de derecho internacional, créditos directo con o sin tasa compensada en los que podamos convenir una participación en beneficio de las entidades territoriales para la financiación de proyectos de inversión en los sectores y subsectores elegibles de Findeter</p><br />
              <p  className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">Conforme a los establecido por el Gobierno Nacional en el decreto 468 de 2020, Findeter está autorizado a otorgar crédito directo a departamentos, municipios y distritos para financiar proyectos y actividades de inversión en los sectores y subsectores financiables por Findeter.</p>
              <div className="flex justify-center"><img
                src="https://storage.googleapis.com/productos-f.appspot.com/Sectores_0.png"
                width="800"
                height="800"
                alt="Sectores Credito Directo"
                className="center mx-auto w-full overflow-hidden rounded-xl object-bottom"
              /></div>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              <strong>Crédito directo con tasa compensada para Covid – 19:</strong>
 

 Otorgamos créditos directos con tasa compensada, dirigidos a financiar proyectos y actividades en los sectores elegibles para mitigar la crisis ocasionada por el Covid -19, impedir la extensión de sus efectos en el territorio nacional, atender la demanda actual de recursos para la reactivación económica y mantener la operación y gestión de las entidades territoriales.
 
  
 Crédito directo con tasa compensada:
  
 
 Otorgamos créditos directos con tasa compensada, prioritariamente a las entidades territoriales para la financiación de proyectos de inversión en los sectores y subsectores elegibles de Findeter. 
 
  
 
 Crédito directo sindicado con o sin tasa compensada:
  
 
 Otorgamos junto a entidades de derecho internacional, créditos directo con o sin tasa compensada en los que podamos convenir una participación en beneficio de las entidades territoriales para la financiación de proyectos de inversión en los sectores y subsectores elegibles de Findeter.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex gap-2">
                <Input type="email" placeholder="Ingrese su correo electrónico" className="max-w-lg flex-1" />
                <Button type="submit">Empezar</Button>
              </form>
              <p className="text-xs text-muted-foreground">
                Al registrarse, acepta nuestros{" "}
                <Link href="#" className="underline underline-offset-2" prefetch={false}>
                  Términos de Servicio
                </Link>
                .
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Acme Inc. Todos los derechos reservados.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Términos de Servicio
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacidad
          </Link>
        </nav>
      </footer>
    </div>
  )
}

