/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7tvetC30sDg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Taviraj } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function CreditoDirecto2() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-4 lg:py-12 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">Líneas de Crédito Directo</h1>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Ideal para financiar, con tasa compensada, la actualización catastral para lograr las metas y objetivos de los planes de desarrollo. 

                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/compromiso-reactivacion-colombia-2.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Reactivación Colombia Tramo 2</h3>
                <p className="text-muted-foreground text-center">
                Línea mixta para inversiones en proyectos de transición energética y financiación para capital de trabajo que genere mitigación de gases de efectos invernadero.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="/compromiso-reactivacion-colombia-2"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/catastro-multiproposito.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Catastro Multipropósito.</h3>
                <p className="text-muted-foreground text-center">
                Ideal para financiar, con tasa compensada, la actualización catastral para lograr las metas y objetivos de los planes de desarrollo.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div><div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/inversion-rural.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Inversión rural, impulsando el progreso de las regiones.</h3>
                <p className="text-muted-foreground text-center">
                Inversiones relacionadas con paneles solares, maquinaria amarilla y transporte especializado que impacten regiones rurales.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/eficiencia-energetica.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Eficiencia Energética y Conectividad Virtual</h3>
                <p className="text-muted-foreground text-center">
                Línea mixta para inversiones en proyectos de transición energética y financiación para capital de trabajo que genere mitigación de gases de efectos invernadero.

                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/compromiso-valle-del-cauca.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Valle Del Cauca</h3>
                <p className="text-muted-foreground text-center">
                Junto a la gobernación, apoyamos a los municipios del departamento para que financien proyectos de inversión que dinamicen su economía, reactiven el tejido social y generen empleo.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/mitigacion-fenomeno-del-nino.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Mitigación Fenómeno del Niño
                </h3>
                <p className="text-muted-foreground text-center">
                Con tasa compensada financiamos capital de trabajo y liquidez a las Empresas de Distribución y Comercialización de Energía Eléctrica que hayan aplicado a la opción tarifaria establecida por la CREG.


                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                ¿Como funciona el Crédito Directo?
              </h2>
              <div className="flex justify-center"><img
                src="https://storage.googleapis.com/productos-f.appspot.com/credito-directo.jpg"
                width="400"
                height="307"
                alt="Sectores Credito Directo"
                className="center mx-auto overflow-hidden rounded-xl object-bottom"
              /></div>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Findeter ofrece <strong>crédito directo</strong> a departamentos, municipios y distritos para financiar proyectos en <strong>sectores estratégicos</strong>, que mejoren la calidad de vida en las regiones, conforme a lo establecido por el Gobierno Nacional en el Decreto 468 de 2020. A diferencia del crédito de redescuento, <strong>no requiere</strong> la participación de intermediarios financieros. El desembolso de los recursos se realizará después de la evaluación de la solicitud y aprobación de garantías. 
Las líneas de crédito directo pueden incluir tasas compensadas que permiten <strong>obtener mejores tasas de interés</strong>. 
</p><br />
              <p  className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">Conforme a los establecido por el Gobierno Nacional en el decreto 468 de 2020, Findeter está autorizado a otorgar crédito directo a departamentos, municipios y distritos para financiar proyectos y actividades de inversión en los sectores y subsectores financiables por Findeter.</p>
              <ol  className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed"><li>Transporte</li>
Salud
Desarrollo urbano y vivienda
Educación 
Minero energético
Industria creativa y cultural
Medio Ambiente
Telecomunicaciones 
Agua potable y saneamiento básico
Saneamiento Fiscal
Turismo
Deporte y recreación 
</ol>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              <strong>Crédito directo con tasa compensada para Covid – 19:</strong>
 

 Otorgamos créditos directos con tasa compensada, dirigidos a financiar proyectos y actividades en los sectores elegibles para mitigar la crisis ocasionada por el Covid -19, impedir la extensión de sus efectos en el territorio nacional, atender la demanda actual de recursos para la reactivación económica y mantener la operación y gestión de las entidades territoriales.
 
  
 Crédito directo con tasa compensada:
  
 
 Otorgamos créditos directos con tasa compensada, prioritariamente a las entidades territoriales para la financiación de proyectos de inversión en los sectores y subsectores elegibles de Findeter. 
 
  
 
 Crédito directo sindicado con o sin tasa compensada:
  
 
 Otorgamos junto a entidades de derecho internacional, créditos directo con o sin tasa compensada en los que podamos convenir una participación en beneficio de las entidades territoriales para la financiación de proyectos de inversión en los sectores y subsectores elegibles de Findeter.
              </p>
            </div>

          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Acme Inc. PAGINA DE PRUEBA.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Términos de Servicio
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacidad
          </Link>
        </nav>
      </footer>
    </div>
  )
}

