/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7tvetC30sDg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Taviraj } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"



export function CreditoDirecto2() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-4 lg:py-12 bg-muted">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div><h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-4xl">
              ¿Qué es crédito directo?
              </h2><p className="py-5 max-w-[900px]  md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">Es la modalidad mediante la cual Findeter otorga créditos sin intermediación de bancos comerciales a entidades territoriales con o sin tasa compensada y dirigidos a financiar proyectos y actividades en 12 sectores estratégicos.</p></div>
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">Líneas de Crédito Directo</h1>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Findeter otorga crédito directo, sin intermediarios financieros, a departamentos, municipios y distritos, para financiar proyectos en 12 sectores estratégicos.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-6 py-12 sm:grid-cols-2 lg:grid-cols-3 lg:gap-12">
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/compromiso-reactivacion-colombia-2.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Reactivación Colombia Tramo 2</h3>
                <p className="text-muted-foreground text-center">
                Línea mixta para inversiones en proyectos de transición energética y financiación para capital de trabajo que genere mitigación de gases de efectos invernadero.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="/compromiso-reactivacion-colombia-2"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/catastro-multiproposito.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Catastro Multipropósito.</h3>
                <p className="text-muted-foreground text-center">
                Ideal para financiar, con tasa compensada, la actualización catastral para lograr las metas y objetivos de los planes de desarrollo.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div><div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/inversion-rural.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Inversión rural, impulsando el progreso de las regiones.</h3>
                <p className="text-muted-foreground text-center">
                Inversiones relacionadas con paneles solares, maquinaria amarilla y transporte especializado que impacten regiones rurales.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/eficiencia-energetica.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Eficiencia Energética y Conectividad Virtual</h3>
                <p className="text-muted-foreground text-center">
                Línea mixta para inversiones en proyectos de transición energética y financiación para capital de trabajo que genere mitigación de gases de efectos invernadero.

                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/compromiso-valle-del-cauca.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Valle Del Cauca</h3>
                <p className="text-muted-foreground text-center">
                Junto a la gobernación, apoyamos a los municipios del departamento para que financien proyectos de inversión que dinamicen su economía, reactiven el tejido social y generen empleo.
                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
              <div className="grid gap-1">
              <img
                src="https://storage.googleapis.com/productos-f.appspot.com/mitigacion-fenomeno-del-nino.jpg"
                width="300"
                height="306"
                alt="Credito Directo"
                className="mx-auto overflow-hidden rounded-xl object-bottom sm:w-full"
              />
                <h3 className="text-lg font-bold text-center">Compromiso Mitigación Fenómeno del Niño
                </h3>
                <p className="text-muted-foreground text-center">
                Con tasa compensada financiamos capital de trabajo y liquidez a las Empresas de Distribución y Comercialización de Energía Eléctrica que hayan aplicado a la opción tarifaria establecida por la CREG.


                </p>
                <div className="flex justify-center flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 text-center"
                    prefetch={false}
                  >
                    Condiciones y requisitos
                  </Link>
                  
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container grid items-center justify-center  gap-4 px-4 md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                ¿Como funciona el Crédito Directo?
              </h2>
              <div className="flex justify-center"><img
                src="https://storage.googleapis.com/productos-f.appspot.com/credito-directo.jpg"
                width="400"
                height="307"
                alt="Sectores Credito Directo"
                className="center mx-auto overflow-hidden rounded-xl object-bottom"
              /></div>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Findeter ofrece <strong>crédito directo</strong> a departamentos, municipios y distritos para financiar proyectos en <strong>sectores estratégicos</strong>, que mejoren la calidad de vida en las regiones, conforme a lo establecido por el Gobierno Nacional en el Decreto 468 de 2020. A diferencia del crédito de redescuento, <strong>no requiere</strong> la participación de intermediarios financieros. El <strong>desembolso</strong> de los recursos se realizará después de la evaluación de la solicitud y aprobación de garantías. <br /> 
Las líneas de crédito directo pueden incluir tasas compensadas que permiten <strong>obtener mejores tasas de interés</strong>. 
</p><br />
              <div className="bg-muted">
                <h3 className="text-3xl ml-5 pt-5"><strong>Sectores de la economía.</strong></h3><p  className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">En Findeter acompañamos proyectos con el fín social en 12 sectores de la economía a través de financiación y asistencia técnica.</p>
              <ol  className="p-5 list-decimal mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed"><li>Transporte
                <ol className="list-disc ml-10"><li><strong>Vial:</strong> Red primaria, secundaria y terciaria de carreteras.
Señalización de vías y redes de ayuda.
Vías urbanas
Semaforización y señalización de vías urbanas 
Industria vial (industrias asociadas al transporte vial)
</li>
                <li><strong>Férreo:</strong> Puertos férreos
Vías férreas
Industria férrea (industrias asociadas al transporte férreo)

                </li>
                <li><strong>Fluvial:</strong> Puertos fluviales
Canales fluviales
Industria fluvial (industrias asociadas al transporte fluvial)

                </li>
                <li><strong>Aéreo:</strong> Terminales de transporte aéreo (incluyendo pistas)
Industria aeronáutica (industrias asociadas al transporte aéreo)
</li>
                <li><strong>Marítimo</strong></li>
                <li><strong>Transporte urbano, carga y pasajeros</strong>
</li></ol>
              </li>
              <li>PENDIENTE AJUSTE OTROS SUBSECTORES Salud</li>
              <li>Desarrollo urbano y vivienda</li>
              <li>Educación </li>
              <li>Minero energético</li>
              <li>Industria creativa y cultural</li>
              <li>Medio Ambiente</li>
              <li>Telecomunicaciones </li>
              <li>Agua potable y saneamiento básico</li>
              <li>Saneamiento Fiscal</li>
              <li>Turismo</li>
              <li>Deporte y recreación</li>










 
</ol></div>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              <strong>Circulares externas:</strong>
 

 TEXTO CIRCULARES EXTERNAS POR DEFINIR.
              </p>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              <strong>Reglamento de Crédito Directo:</strong>
 

 TEXTO REGLAMENTO CREDITO DIRECTO.
              </p>
              <h2 className="pt-10 text-2xl font-bold tracking-tighter sm:text-3xl">Transforme Su Territorio Con Nosotros</h2>
            <p className="text-muted-foreground">
            Permítanos contactarlo para conocer sus necesidades y ayudarlo a cumplir sus planes de desarrollo. 

            </p>
              <form className="space-y-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Input type="text" placeholder="Nombre" className="w-full" />
              <Input type="text" placeholder="Apellido" className="w-full" />
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Input type="text" placeholder="Entidad" className="w-full" />
              <Input type="text" placeholder="Cargo" className="w-full" />
            </div>

            <div className="grid gap-4">
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Tipo De Entidad" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Privada</SelectItem>
                <SelectItem value="product2">Pública</SelectItem>
                <SelectItem value="service1">Mixta</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
        </div>


            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Input type="email" placeholder="Email" className="w-full" />
            <Input id="phone" type="tel" placeholder="Celular" />
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Departamento" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Amazonas</SelectItem>
                <SelectItem value="product2">Antioquia</SelectItem>
                <SelectItem value="service1">Arauca</SelectItem>
                <SelectItem value="service2">Atlántico</SelectItem>
                <SelectItem value="service2">Bolivar</SelectItem>
                <SelectItem value="service2">Boyacá</SelectItem>
                <SelectItem value="service2">Caldas</SelectItem>
                <SelectItem value="service2">Caquetá</SelectItem>
                <SelectItem value="service2">Casanare</SelectItem>
                <SelectItem value="service2">Cauca</SelectItem>
                <SelectItem value="service2">Cesar</SelectItem>
                <SelectItem value="service2">Chocó</SelectItem>
                <SelectItem value="service2">Córdoba</SelectItem>
                <SelectItem value="service2">Cundinamarca</SelectItem>
                <SelectItem value="service2">Guainía</SelectItem>
                <SelectItem value="service2">Guaviare</SelectItem>
                <SelectItem value="service2">Huila</SelectItem>
                <SelectItem value="service2">La Guajira</SelectItem>
                <SelectItem value="service2">Magdalena</SelectItem>
                <SelectItem value="service2">Meta</SelectItem>
                <SelectItem value="service2">Nariño</SelectItem>
                <SelectItem value="service2">Norte de Santander</SelectItem>
                <SelectItem value="service2">Putumayo</SelectItem>
                <SelectItem value="service2">Quindio</SelectItem>
                <SelectItem value="service2">Risaralda</SelectItem>
                <SelectItem value="service2">San Andrés y Providencia</SelectItem>
                <SelectItem value="service2">Santander</SelectItem>
                <SelectItem value="service2">Sucre</SelectItem>
                <SelectItem value="service2">Tolima</SelectItem>
                <SelectItem value="service2">Valle Del Cauca</SelectItem>
                <SelectItem value="service2">Vaupes</SelectItem>
                <SelectItem value="service2">Vichada</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Municipio" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Municipio 1</SelectItem>
                <SelectItem value="product2">Municipio 2</SelectItem>
                <SelectItem value="service1">Municipio 3</SelectItem>
                <SelectItem value="service2">Municipio 4</SelectItem>
                <SelectItem value="service2">Municipio 5</SelectItem>
                <SelectItem value="service2">Municipio 6</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
            </div>
            <Textarea placeholder="Cuéntenos acerca de sus proyectos (costo estimado de la inversión, uso, sector, entre otros)" className="w-full" rows={4} />
            <div className="flex items-center space-x-2">
            <Checkbox id="terms" />
            <Label htmlFor="terms">Acepta nuestros terminos y condiciones.</Label>
          </div>
            <Button type="submit" className="w-full">
              Enviar
            </Button>
          </form>
            </div>

          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Acme Inc. PAGINA DE PRUEBA.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Términos de Servicio
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacidad
          </Link>
        </nav>
      </footer>
    </div>
  )
}

