/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/12xYo57U9NL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectGroup, SelectItem } from "@/components/ui/select"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"

export function RedescuentoReactivaColombia() {
  return (
    <div className="w-full py-4 md:py-4 lg:py-4">
      <div className="container grid gap-8 px-4 md:grid-cols-2 md:gap-12 md:px-6">
        <div className="space-y-1">
          <div className="space-y-1">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Programa Reactiva Colombia
            </h2>
            <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Impulsamos la economía dinámica, incluyente y sostenible a través de proyectos de infraestructura en sectores clave para el desarrollo del país.

            </p>
          </div>
          <div className="space-y-4">
            <h3 className="mt-5 text-3xl font-bold tracking-tighter sm:text-2xl md:text-2xl">
              Condiciones
            </h3>
            <h4 className="max-w-[600px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            <strong>Beneficiarios: </strong></h4>
            <ul className="space-y-4"><li className="list-disc">Empresas del sector privado.</li>
            <li className="list-disc">Departamentos, municipios y distritos.</li>
            <li className="list-disc">Entidades públicas y entidades descentralizadas del orden nacional y territorial
            </li>
            </ul>
            <h4 className="max-w-[600px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            <strong>Uso de los Recursos: </strong></h4>
            <ul className="space-y-4"><li className="list-disc">Gastos de inversión que permitan financiar todas las inversiones relacionadas con la infraestructura para el desarrollo sostenible de las regiones.

            </li>
            </ul>
            <h4 className="max-w-[600px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            <strong>Tasa Final: </strong></h4>
            <ul className="space-y-4"><li className="list-disc"><strong>Tasa de interés al intermediario:</strong>

Desde IBR + 0,8% M.V.</li>
<li className="list-disc"><strong>
Margen de intermediación:</strong>

Hasta 400 puntos básicos sobre la tasa de redescuento de Findeter.</li>
            </ul>
          </div>

          <div className="mt-20">
                        <h4 className="max-w-[600px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            <strong>Plazo total: </strong></h4>
            <p>Hasta 12 años con hasta 2 años de periodo de gracia a capital.</p>
          </div>

                    <div className="mt-20">
                        <h4 className="max-w-[600px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            <strong>Vigencia de la Línea: </strong></h4>
            <p>Hasta el 31 de diciembre de 2024 o hasta agotar los recursos, lo que primero ocurra.</p>
          </div>
        </div>
        <div className="space-y-4  bg-muted p-5">
          <div className="space-y-2">
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Transforme Su Territorio Con Nosotros</h2>
            <p className="text-muted-foreground">
            Permítanos contactarlo para conocer sus necesidades y ayudarlo a cumplir sus planes de desarrollo. 

            </p>
          </div>
          <form className="space-y-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Input type="text" placeholder="Nombre" className="w-full" />
              <Input type="text" placeholder="Apellido" className="w-full" />
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <Input type="text" placeholder="Entidad" className="w-full" />
              <Input type="text" placeholder="Cargo" className="w-full" />
            </div>

            <div className="grid gap-4">
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Tipo De Entidad" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Privada</SelectItem>
                <SelectItem value="product2">Pública</SelectItem>
                <SelectItem value="service1">Mixta</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
        </div>


            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Input type="email" placeholder="Email" className="w-full" />
            <Input id="phone" type="tel" placeholder="Celular" />
            </div>
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Departamento" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Amazonas</SelectItem>
                <SelectItem value="product2">Antioquia</SelectItem>
                <SelectItem value="service1">Arauca</SelectItem>
                <SelectItem value="service2">Atlántico</SelectItem>
                <SelectItem value="service2">Bolivar</SelectItem>
                <SelectItem value="service2">Boyacá</SelectItem>
                <SelectItem value="service2">Caldas</SelectItem>
                <SelectItem value="service2">Caquetá</SelectItem>
                <SelectItem value="service2">Casanare</SelectItem>
                <SelectItem value="service2">Cauca</SelectItem>
                <SelectItem value="service2">Cesar</SelectItem>
                <SelectItem value="service2">Chocó</SelectItem>
                <SelectItem value="service2">Córdoba</SelectItem>
                <SelectItem value="service2">Cundinamarca</SelectItem>
                <SelectItem value="service2">Guainía</SelectItem>
                <SelectItem value="service2">Guaviare</SelectItem>
                <SelectItem value="service2">Huila</SelectItem>
                <SelectItem value="service2">La Guajira</SelectItem>
                <SelectItem value="service2">Magdalena</SelectItem>
                <SelectItem value="service2">Meta</SelectItem>
                <SelectItem value="service2">Nariño</SelectItem>
                <SelectItem value="service2">Norte de Santander</SelectItem>
                <SelectItem value="service2">Putumayo</SelectItem>
                <SelectItem value="service2">Quindio</SelectItem>
                <SelectItem value="service2">Risaralda</SelectItem>
                <SelectItem value="service2">San Andrés y Providencia</SelectItem>
                <SelectItem value="service2">Santander</SelectItem>
                <SelectItem value="service2">Sucre</SelectItem>
                <SelectItem value="service2">Tolima</SelectItem>
                <SelectItem value="service2">Valle Del Cauca</SelectItem>
                <SelectItem value="service2">Vaupes</SelectItem>
                <SelectItem value="service2">Vichada</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
          <Select>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Municipio" />
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="product1">Municipio 1</SelectItem>
                <SelectItem value="product2">Municipio 2</SelectItem>
                <SelectItem value="service1">Municipio 3</SelectItem>
                <SelectItem value="service2">Municipio 4</SelectItem>
                <SelectItem value="service2">Municipio 5</SelectItem>
                <SelectItem value="service2">Municipio 6</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
            </div>
            <Textarea placeholder="Cuéntenos acerca de sus proyectos (costo estimado de la inversión, uso, sector, entre otros)" className="w-full" rows={4} />
            <div className="flex items-center space-x-2">
            <Checkbox id="terms" />
            <Label htmlFor="terms">Acepta nuestros terminos y condiciones.</Label>
          </div>
            <Button type="submit" className="w-full">
              Iniciar Proceso
            </Button>
          </form>
          <p className="text-sm">* Solicitudes únicamente para personas jurídicas.</p>
          <p><strong>Caribe:</strong> 320 490 2593 / 301 754 8949 <br /> <strong>Noroccidental:</strong> 314 336 4910 / 316 345 4257<br /><strong>Nororiental:</strong> 321975 9881 / 320 490 2576<br /><strong>Eje Cafetero:</strong> 320 490 2594 / 322 523 8014<br /><strong>Pacífico:</strong> 314 682 4441 / 312 818 2460<br /><strong>Centro:</strong> 322 214 1371 / 315 333 8876<br />
          <strong>Línea nacional gratuita:</strong> 01 8000 11 66 22 
<br />Consulte el listado de gerentes de cuenta de Findeter
</p>
        </div>
      </div>
      <div className="mt-10 bg-muted container grid gap-8 px-4 md:grid-cols-1 md:gap-12 md:px-6">
        <h2 className="text-3xl py-5"><strong>Condiciones</strong></h2>
    <ol className="list-decimal p-5"><li>El banco de primer piso, de acuerdo con su análisis, determinará el monto final del crédito a otorgar a los beneficiarios.</li>
    <li>El desembolso de las operaciones está sujeto a la disponibilidad de recursos que tenga Findeter y a la revisión y validación de los documentos legales soporte por parte de la Financiera, así como al cumplimiento de nuestro Reglamento para Operaciones de Crédito de Redescuento. </li>
    <li>El uso de los recursos es responsabilidad del beneficiario y el control sobre el uso corresponde al intermediario financiero.</li></ol>

        </div>

        <div className="mt-10 container grid gap-8 px-4 md:grid-cols-1 md:gap-12 md:px-6">
        <h2 className="text-3xl py-5"><strong>Requisitos:</strong></h2>
        <ol className="list-decimal p-5"><li>Aplica para proyectos de inversión que cuenten con la viabilidad del Ministerio o entidad correspondiente.</li>
    <li>Estar dentro de los sectores financiables que aplican al Programa Reactiva Colombia.</li>
    </ol>
        
        </div>

        <div className="mt-10 bg-muted container grid gap-8 px-4 md:grid-cols-1 md:gap-12 md:px-6">
        <h2 className="text-3xl py-5"><strong>Circular</strong></h2>
        <ol className="list-disc p-5"><li className="p-5">Consulte la circular del programa Reactiva Colombia.<Button className="btn">
        Descargue la circular
            </Button></li>
        <li className="p-5">Circular Externa # 10 - Programa Reactiva Colombia VF DC.<Button className="btn">
        Descargue la circular
            </Button></li>
        </ol>
        </div>

        <div className="mt-10 container grid gap-8 px-4 md:grid-cols-1 md:gap-12 md:px-6">
        

        </div>

        
        

    </div>
  )
}
